# typed: strict
# frozen_string_literal: true

# Smaller Please — Homebrew formula TEMPLATE (macOS Apple Silicon).
#
# HOW THIS FILE IS USED
#   This committed file is the reviewable template. The URL and SHA-256 placeholders are
#   substituted from a built release artifact by scripts/render-homebrew-formula.sh (never
#   hand-type a SHA). The formula intentionally declares NO `version` stanza: Homebrew derives
#   the version natively from the release URL / artifact filename
#   (`smaller-please-<canonical>-macos-<arch>.tar.gz`), so an explicit stanza would be redundant
#   (and `brew audit --strict --online` rejects it). The canonical version is still the single
#   product version: the render step refuses a URL/artifact filename that does not encode the
#   artifact's canonical release-manifest.json version.
#
# SCOPE
#   The formula installs the prebuilt release artifact only. It does not build from source,
#   does not depend on FFmpeg, and never mutates $HOME, registers the Native Host, touches
#   Chrome, or runs `smaller setup`. Only macos-arm64 is built/tested today; the Intel branch
#   refuses until an x86_64 artifact exists (macos-x86_64 is Planned).
#
# See docs/RELEASE_ARTIFACT.md and packaging/homebrew/README.md.
# RENDERED-FORMULA: generated by scripts/render-homebrew-formula.sh (safe to overwrite)
class SmallerPlease < Formula
  desc "Optimize local media before sending it to AI agents"
  homepage "https://github.com/wberry9813/Smaller-Please"
  url "https://github.com/wberry9813/Smaller-Please/releases/download/v0.1.0-beta.5/smaller-please-0.1.0-beta.5-macos-arm64.tar.gz"
  sha256 "571be9918e13b13f2f64ca39af2bc75bc97173c23ae680f8e1cec954f5572080"
  license "MIT"

  # Apple Silicon only: Intel (x86_64) is not supported. `depends_on arch:` refuses an Intel
  # install at install time; do not use `odie` here, which would raise while Homebrew parses the
  # formula during `brew tap` and make the whole tap invalid.
  depends_on arch: :arm64
  depends_on macos: :monterey

  def install
    bin.install "bin/smaller"
    bin.install "bin/contextslim"
    pkgshare.install "share/smaller-please/extension"
  end

  def caveats
    <<~EOS
      Finish setup as your user (this formula never runs it for you):
        1. Run:  smaller setup
        2. Open chrome://extensions, enable Developer mode, click "Load unpacked", and select:
             ~/Applications/Smaller Please Extension

      Always load the extension from that visible path, never from the Homebrew Cellar.

      Media: `smaller setup` uses an existing FFmpeg, or (on an interactive terminal only) may
      offer `brew install ffmpeg`. FFmpeg is NOT a dependency of this formula.

      `brew uninstall smaller-please` removes only Homebrew-managed files. Your config,
      cache/store, staged extension, Native Host files, and Chrome data are left in place.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/smaller --version")
  end
end
