# typed: strict
# frozen_string_literal: true

# Smaller Please — Homebrew formula TEMPLATE (macOS Apple Silicon).
#
# HOW THIS FILE IS USED
#   This committed file is the reviewable template. The URL and SHA-256 placeholders are
#   substituted from a built release artifact by scripts/render-homebrew-formula.sh (never
#   hand-type a SHA). The formula intentionally declares NO `version` stanza: Homebrew derives
#   the version natively from the release URL / artifact filename
#   (`smaller-please-<canonical>-macos-<arch>.tar.gz`), so an explicit stanza would be redundant
#   (and `brew audit --strict --online` rejects it). The canonical version is still the single
#   product version: the render step refuses a URL/artifact filename that does not encode the
#   artifact's canonical release-manifest.json version.
#
# SCOPE
#   The formula installs the prebuilt release artifact only. It does not build from source,
#   does not depend on FFmpeg, and never mutates $HOME, registers the Native Host, touches
#   Chrome, or runs `smaller setup`. Only macos-arm64 is built/tested today; the Intel branch
#   refuses until an x86_64 artifact exists (macos-x86_64 is Planned).
#
# See docs/RELEASE_ARTIFACT.md and packaging/homebrew/README.md.
# RENDERED-FORMULA: generated by scripts/render-homebrew-formula.sh (safe to overwrite)
class SmallerPlease < Formula
  desc "Optimize local media before sending it to AI agents"
  homepage "https://github.com/wberry9813/Smaller-Please"
  url "https://github.com/wberry9813/Smaller-Please/releases/download/v0.1.0/smaller-please-0.1.0-macos-arm64.tar.gz"
  sha256 "e3dc659e6c7c13d2856d8e3a7699f1ffb8d4335fbe5d7a11770f6f3d4e084b82"
  license "MIT"

  # Homebrew's version comparison ranks the prerelease `0.1.0-beta.5` BELOW the historical
  # base-version `0.1.0` formula (Beta.4 deliberately used the base version), so without this
  # stanza `brew upgrade` reports "0.1.0 already installed" and never crosses that boundary.
  # `version_scheme 1` tells Homebrew that the prior scheme (scheme 0, e.g. the installed Beta.4)
  # sorts lower, so a prerelease beta upgrades over the historical `0.1.0` install. This is an
  # independent Homebrew stanza, not a product version: the Formula version itself stays
  # URL-derived and canonical (the formula still declares no `version` stanza).
  version_scheme 1

  # Apple Silicon only: Intel (x86_64) is not supported. `depends_on arch:` refuses an Intel
  # install at install time; do not use `odie` here, which would raise while Homebrew parses the
  # formula during `brew tap` and make the whole tap invalid.
  depends_on arch: :arm64
  depends_on macos: :monterey

  def install
    bin.install "bin/smaller"
    bin.install "bin/contextslim"
    pkgshare.install "share/smaller-please/extension"
    pkgshare.install "share/smaller-please/skills"
  end

  def caveats
    <<~EOS
      Smaller, Please installed.

      CLI:
        smaller doctor

      Browser extension:
        The Chrome extension is included with this installation.

        Run:
          smaller setup

        Then show the extension folder:
          smaller extension path

        In Chrome:
          1. Open chrome://extensions
          2. Enable Developer mode
          3. Click Load unpacked
          4. Select the folder printed above

      Agent Skill:
        The Smaller, Please Agent Skill is included with this installation.

        Run:
          smaller get skills

        Give the output to your AI agent.

      FFmpeg is not a dependency of this formula. `smaller setup` may use an existing FFmpeg,
      or (on an interactive terminal only) offer `brew install ffmpeg`.

      `brew uninstall smaller-please` removes only Homebrew-managed files. Your config,
      cache/store, staged extension, Native Host files, and Chrome data are left in place.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/smaller --version")
  end
end
